services:
  - type: web
    name: firewall-viewer
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOTP_SECRET
        value: U3KQHZMQ4UMNVTZYXTPGJ2AGLBRPZR5L
      - key: WEBHOOK_URL
        value: http://157.180.126.133:5001
      - key: WEBHOOK_SECRET
        value: linda-firewall-webhook-secret-2026
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
